version: '3.8'

services:
  trubft-standalone:
    image: trubft:TruBFT
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TRUBFT_MODE=standalone
      - TRUBFT_N=4
      - TRUBFT_T=1
      - TRUBFT_B=100
      - TRUBFT_TX=-1

  trubft-node:
    image: trubft:TruBFT
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TRUBFT_MODE=distributed
      - TRUBFT_N=4
      - TRUBFT_T=1
      - TRUBFT_B=100
      - TRUBFT_TX=-1
      - TRUBFT_MY_ID=0
      - TRUBFT_VERSION=1
