#!/bin/bash

# BFT 一键运行脚本
# 用法: ./helper.sh
#
# 显示所有分支的 docker-compose 启动命令

echo "=========================================="
echo "  BFT 分支一键运行"
echo "=========================================="
echo ""
echo "直接复制运行以下命令："
echo ""
echo "  # ACS/VABA (N=4, t=1, B=100)"
echo "  git checkout -f ACS && docker build -t trubft:ACS . && docker-compose run --rm vaba"
echo ""
echo "  # TruBFT SGX (N=4, t=1, B=100)"
echo "  git checkout -f TruBFT && docker build -t trubft:TruBFT . && docker-compose run --rm trubft-standalone"
echo ""
echo "  # TruBFT-None-SGX / Beat (N=4, t=1, B=100)"
echo "  git checkout -f TruBFT-None-SGX && docker build -t trubft:TruBFT-None-SGX . && docker-compose run --rm beat"
echo ""
echo "  # Beat-PY3 (N=4, t=1, B=100)"
echo "  git checkout -f Beat-PY3 && docker build -t trubft:Beat-PY3 . && docker-compose run --rm trubft-standalone"
echo ""
echo "  # Beat-Localcoin (N=4, t=1, B=100)"
echo "  git checkout -f Beat-Localcoin-PY3 && docker build -t trubft:Beat-Localcoin-PY3 . && docker-compose run --rm beat-localcoin"
echo ""
echo "  # Dumbo BFT (N=4, f=1, B=1000, E=20)"
echo "  git checkout -f Dumbo\\&HB && conda activate dumbo && ./run_local_network_test.sh 4 1 1000 20"
echo ""
echo "=========================================="
echo "  自定义参数"
echo "=========================================="
echo ""
echo "  编辑 docker-compose.yml 修改环境变量："
echo "    ACS:            ACS_N, ACS_T, ACS_B"
echo "    TruBFT:         TRUBFT_N, TRUBFT_T, TRUBFT_B"
echo "    Beat:           BFT_N, BFT_T, BFT_B"
echo "    Beat-Localcoin: BFT_N, BFT_T, BFT_B"
echo "    Dumbo:          命令行参数"
echo ""
